project:
  type: website
  output-dir: docs

website:
  title: "Will Corbin - Analytics Portfolio"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: quickhitters.qmd
        text: Quick Hitters
      - text: Projects
        href: projects.qmd
        menu:
        - href: projects/draft_model/draft_model_2025_writeup.ipynb
          text: Draft Prospect Ratings
      - href: https://sites.google.com/georgetown.edu/georgetown-basketball?usp=sharing
        text: Georgetown Internal Site
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true