project:
  type: website
  output-dir: docs

website:
  title: "Will Corbin - Analytics Portfolio"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: quickhitters.qmd
        text: Quick Hitters
      - href: https://willcorbin.quarto.pub/georgetown-basketball/
        text: Georgetown
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true