project:
  type: website

website:
  title: "Will Corbin - Analytics Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quickhitters.qmd
        text: Quick Hitters
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true